/* 位置と大きさは managed_switch.vhd の generic に合わせる。 */
MEMORY
{
  IMEM : ORIGIN = 0x00000000, LENGTH = 32K
  DMEM : ORIGIN = 0x80000000, LENGTH = 32K
}

REGION_ALIAS("REGION_TEXT",   IMEM);
REGION_ALIAS("REGION_RODATA", IMEM);
REGION_ALIAS("REGION_DATA",   DMEM);
REGION_ALIAS("REGION_BSS",    DMEM);
REGION_ALIAS("REGION_HEAP",   DMEM);
REGION_ALIAS("REGION_STACK",  DMEM);
