#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pymupdf4llm>=0.0.17",
# ]
# ///
"""Convert datasheet PDFs to Markdown.

Usage:
    uv run tools/pdf2md/pdf2md.py path/to/foo.pdf ...     # datasheets/foo.md を生成
    uv run tools/pdf2md/pdf2md.py --images foo.pdf        # 図も PNG で書き出す

PDF はリポジトリに置かないため、出力は PDF の場所によらず datasheets/ に同名の .md として保存する。
--images 指定時は <name>_images/ に図を書き出し、Markdown から相対参照する。
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

import pymupdf
import pymupdf4llm

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DIR = REPO_ROOT / "datasheets"

# 図だけのページではフッタ検出が効かず定型文が本文に残るため、この回数以上繰り返す段落を定型文の候補とする。
# 本文でも同じ説明文が繰り返されることがあるため、ページの上端か下端にある文字列と一致する候補だけを消す。
BOILERPLATE_MIN_COUNT = 5
BOILERPLATE_MIN_LEN = 40
MARGIN_RATIO = 0.1


def margin_texts(pdf: Path) -> list[str]:
    texts = []
    with pymupdf.open(pdf) as doc:
        for page in doc:
            height = page.rect.height
            blocks = [
                b[4]
                for b in page.get_text("blocks")
                if b[3] < height * MARGIN_RATIO or b[1] > height * (1 - MARGIN_RATIO)
            ]
            texts.append(" ".join(" ".join(blocks).split()))
    return texts


def strip_boilerplate(pages: list[str], margins: list[str]) -> tuple[str, list[str]]:
    def prose(line: str) -> str | None:
        body = line.removeprefix("> ").strip()
        if len(body) < BOILERPLATE_MIN_LEN or body.startswith(("|", "<!--", "#")):
            return None
        return body

    per_page = [
        Counter(b for b in map(prose, page.splitlines()) if b) for page in pages
    ]
    counts = Counter(b for page_counts in per_page for b in page_counts.elements())
    # 定型文は 1 ページに 1 回しか現れない。同じページで繰り返す段落はレジスタの説明などの本文なので残す
    repeated = [
        b
        for b, n in counts.items()
        if n >= BOILERPLATE_MIN_COUNT
        and all(page_counts[b] <= 1 for page_counts in per_page)
        and any(" ".join(b.split()) in m for m in margins)
    ]

    out = []
    for line in "".join(pages).splitlines():
        if prose(line):
            for b in repeated:
                line = line.replace(b, "")
            if not line.removeprefix(">").strip():
                continue
        out.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)) + "\n", repeated


def convert(pdf: Path, out_dir: Path, images: bool) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"{pdf.stem}.md"

    # ページごとに繰り返される著作権表記・文書番号・ページ番号は本文検索の邪魔になるので除く
    kwargs: dict = {"show_progress": False, "header": False, "footer": False}
    if images:
        img_dir = out_dir / f"{pdf.stem}_images"
        img_dir.mkdir(exist_ok=True)
        kwargs.update(
            write_images=True, image_path=str(img_dir), image_format="png", dpi=150
        )

    chunks = pymupdf4llm.to_markdown(str(pdf), page_chunks=True, **kwargs)
    md, removed = strip_boilerplate(
        [chunk["text"] for chunk in chunks], margin_texts(pdf)
    )
    for b in removed:
        print(f"  removed boilerplate: {b[:80]}")

    if images:
        # 画像パスを Markdown ファイルからの相対パスに揃える
        md = md.replace(str(out_dir) + "/", "")

    header = f"<!-- Generated by tools/pdf2md/pdf2md.py from {pdf.name}. Do not edit by hand. -->\n\n"
    md_path.write_text(header + md, encoding="utf-8")
    print(f"wrote: {md_path}")
    return md_path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("pdfs", nargs="+", type=Path, help="変換する PDF")
    parser.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        default=DEFAULT_DIR,
        help="出力先ディレクトリ (既定は datasheets/)",
    )
    parser.add_argument("--images", action="store_true", help="図を PNG として書き出す")
    args = parser.parse_args()

    for pdf in args.pdfs:
        if not pdf.is_file():
            print(f"not found: {pdf}", file=sys.stderr)
            return 1
    for pdf in args.pdfs:
        convert(pdf.resolve(), args.out_dir.resolve(), args.images)
    return 0


if __name__ == "__main__":
    sys.exit(main())
