/* 位置と大きさは riscv_rust.vhd の generic に合わせる。 */
MEMORY
{
  IMEM : ORIGIN = 0x00000000, LENGTH = 16K
  DMEM : ORIGIN = 0x80000000, LENGTH = 8K
}

REGION_ALIAS("REGION_TEXT",   IMEM);
REGION_ALIAS("REGION_RODATA", IMEM);
REGION_ALIAS("REGION_DATA",   DMEM);
REGION_ALIAS("REGION_BSS",    DMEM);
REGION_ALIAS("REGION_HEAP",   DMEM);
REGION_ALIAS("REGION_STACK",  DMEM);
